### PR TITLE
Two bug fixes and minor coding style revision

### PR DESCRIPTION
**Pull request by krzysztofarendt**
Bug fixes:
1) parameters can be estimated now alone, without state estimation
2) sigma points are not redrawn after covariance matrix update - I did not find any paper advising it

Please note, that I disabled multithreading by hardcoding N_MAX_PROCESSES = 1 in `fmu_pool.py`:
https://github.com/krzysztofarendt/EstimationPy-KA/commit/9a793a11a5554e5c3f7e48daf9a8052637616c8d#diff-1b51491e2092a6feb0aac6913848514c
Multiprocessing didn't work for me, but I can't remember what was the issue.

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @krzysztofarendt.  Except I do not know what https://github.com/lbl-srg/EstimationPy/pull/3/commits/68796652aaeea268c265b4a388b3711c05d48adc does.  Is it needed?

**Comment by dhblum** [comment]
This PR fixes https://github.com/lbl-srg/EstimationPy/issues/4, https://github.com/lbl-srg/EstimationPy/issues/5, https://github.com/lbl-srg/EstimationPy/issues/7 and addresses https://github.com/lbl-srg/EstimationPy/issues/6 and https://github.com/lbl-srg/EstimationPy/issues/8.

**Comment by krzysztofarendt** [comment]
> Thanks @krzysztofarendt. Except I do not know what [6879665](https://github.com/lbl-srg/EstimationPy/commit/68796652aaeea268c265b4a388b3711c05d48adc) does. Is it needed?

My bad. It seems I added a PyCharm configuration file to the repo. I deleted it in https://github.com/lbl-srg/EstimationPy/pull/3/commits/8f847393b8624ca9e6da45bfca8249310644c437

**Comment by dhblum** [comment]
Great, thanks @krzysztofarendt!

**Pull request merged**
